*:8080 {
  root "~/.box"
  disable_symlinks false
  cgi {
  }
  rewrite "^/bin/(.*)" "/ferron/bin.nu/bin/$1" {
    file true
    directory true
    last true
  }
  rewrite "^/box/(.*)" "/ferron/box.nu/box/$1" {
    file true
    directory true
    last true
  }
  rewrite "^/pub/(.*)" "/ferron/pub.nu/pub/$1" {
    file true
    directory true
    last true
  }
  rewrite "^/cache/(.*)" "/ferron/cache.nu/cache/$1" {
    file true
    directory true
    last true
  }
  rewrite "^/(.*)" "/ferron/index.nu/$1" {
    file true
    directory true
    last true
  }
  cgi {
    extension ".nu"
    environment "PREFIX_LEN" "1"
    environment "PUB_ROOT" "PUB_ROOT_PLACEHOLDER"
    environment "CACHE_ROOT" "CACHE_ROOT_PLACEHOLDER"
  }
  console_log
}
