bind =, F1, exec, python3 /etc/hypr/scripts/hypr_toggle.py 1
bind =, F2, exec, python3 /etc/hypr/scripts/hypr_toggle.py 2
bind =, F3, exec, python3 /etc/hypr/scripts/hypr_toggle.py 3
bind =, F4, exec, python3 /etc/hypr/scripts/hypr_toggle.py 4
bind =, F5, exec, python3 /etc/hypr/scripts/hypr_toggle.py 5
bind =, F6, exec, python3 /etc/hypr/scripts/hypr_toggle.py 6
bind =, F7, exec, python3 /etc/hypr/scripts/hypr_toggle.py 7
bind =, F8, exec, python3 /etc/hypr/scripts/hypr_toggle.py 8
bind =, F9, exec, python3 /etc/hypr/scripts/hypr_toggle.py 9
bind =, F10, exec, python3 /etc/hypr/scripts/hypr_toggle.py 10
bind =, F11, exec, python3 /etc/hypr/scripts/hypr_toggle.py 11
bind =, F12, exec, python3 /etc/hypr/scripts/hypr_toggle.py 12
