-- =============================================================================
-- Hyprland 声明式配置（Lua 版） —— 由 NixOS 生成，可经符号链接部署到 ~/.config/hypr
-- 替代旧的 hyprland.conf 格式；Hyprland 0.4x Lua 配置 API（hl.*）
-- 占位符（由 hyprland.nix replaceStrings 注入）：
--   @HYPR_TOGGLE@   -> hypr-toggle 脚本绝对路径
--   @SWITCHER@      -> Alt+Tab 切换器二进制（hyprshell/hyprswitch）
--   @EXTRA_EXEC_ONCE@ -> 其他单元（quickshell）注入的自启命令
-- =============================================================================

hl.config({ autogenerated = true })

-- ── 终端 / 程序 ─────────────────────────────────────────
local terminal = "ghostty"   -- 用户实际终端（非 kitty）

-- ── 显示器 ─────────────────────────────────────────────
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })

-- ── 自启（exec-once）───────────────────────────────────
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("fcitx5 -d")
    hl.exec_cmd("@SWITCHER@ init --show-title --init-sort-type \"recently-focused\" &")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
@EXTRA_EXEC_ONCE@
end)

-- ── 环境变量 ───────────────────────────────────────────
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- ── 常规 / 装饰 ────────────────────────────────────────
hl.config({
    general = {
        gaps_in      = 2,
        gaps_out     = 2,
        border_size  = 2,
        col = {
            active_border   = "rgba(f5a962ff)",
            inactive_border = "rgba(595959aa)",
        },
        layout = "dwindle",
    },

    decoration = {
        rounding = 10,
        shadow = {
            enabled      = true,
            range        = 12,
            offset       = "3 3",
            render_power = 3,
            color        = 0x00000044,
        },
    },

    animations = { enabled = true },

    dwindle = { preserve_split = true },
})

-- ── 输入 ───────────────────────────────────────────────
hl.config({
    input = {
        kb_layout  = "us",
        kb_options = "ctrl:swapcaps",
        follow_mouse = 1,
    },
})

-- ── 键位绑定 ───────────────────────────────────────────
local mainMod = "SUPER"

-- F1-F12 智能窗口切换（hypr-toggle）
hl.bind(", F1",  hl.dsp.exec_cmd("@HYPR_TOGGLE@ 1"))
hl.bind(", F2",  hl.dsp.exec_cmd("@HYPR_TOGGLE@ 2"))
hl.bind(", F3",  hl.dsp.exec_cmd("@HYPR_TOGGLE@ 3"))
hl.bind(", F4",  hl.dsp.exec_cmd("@HYPR_TOGGLE@ 4"))
hl.bind(", F5",  hl.dsp.exec_cmd("@HYPR_TOGGLE@ 5"))
hl.bind(", F6",  hl.dsp.exec_cmd("@HYPR_TOGGLE@ 6"))
hl.bind(", F7",  hl.dsp.exec_cmd("@HYPR_TOGGLE@ 7"))
hl.bind(", F8",  hl.dsp.exec_cmd("@HYPR_TOGGLE@ 8"))
hl.bind(", F9",  hl.dsp.exec_cmd("@HYPR_TOGGLE@ 9"))
hl.bind(", F10", hl.dsp.exec_cmd("@HYPR_TOGGLE@ 10"))
hl.bind(", F11", hl.dsp.exec_cmd("@HYPR_TOGGLE@ 11"))
hl.bind(", F12", hl.dsp.exec_cmd("@HYPR_TOGGLE@ 12"))

-- Alt+Tab 切换器：呼出并在窗口列表前向/反向循环
hl.bind("ALT, TAB",         hl.dsp.exec_cmd("@SWITCHER@ gui --mod-key alt --key tab"))
hl.bind("ALT SHIFT, TAB",   hl.dsp.exec_cmd("@SWITCHER@ gui --mod-key alt --key tab --reverse-key shift"))
-- 松开 Alt 瞬间关闭切换器 GUI（原 bindr；若 Lua 不支持 release 需调整）
hl.bind("ALT, ALT_L",       hl.dsp.exec_cmd("@SWITCHER@ close"), { release = true })

-- 截图
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd("flameshot gui || grim -g \"$(slurp)\" - | swappy -f -"))
-- 电源/退出
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exec_cmd("wlogout"))
-- 应用启动器（Quickshell）
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("quickshell ipc call default toggleLauncher"))

-- 工作区切换 / 移动窗口到工作区
for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- 焦点移动
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- 移动窗口
hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.window.move({ direction = "down" }))

-- ── 窗口规则 ───────────────────────────────────────────
hl.window_rule({
    name  = "float-mpv",
    match = { class = "^(mpv)$" },
    float = true,
    size  = { w = 1280, h = 720 },
    center = true,
})