# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # 以下 UUID 需替换为实际磁盘的 UUID（使用 `lsblk -f` 查看）
    fileSystems."/" =
      { device = "/dev/disk/by-uuid/dfd51d2d-db10-4a63-82d7-10c4f59418e0";
        fsType = "xfs";
      };

    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/8C1A-FBE8";
        fsType = "vfat";
        options = [ "fmask=0022" "dmask=0022" ];
      };

  swapDevices = [ ];

  # 使用 nixos-generate-config 时自动生成，此处设为默认
  networking.useDHCP = lib.mkDefault true;
  # hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
