# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to the host configuration file (default.nix) instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.loader = {
    systemd-boot = {
      enable = true;
      configurationLimit = 5;
    };
    efi.canTouchEfiVariables = true;
    timeout = 3;
  };

  boot.initrd.availableKernelModules = [
    "ata_piix"    # IDE controller (QEMU default chipset)
    "ahci"        # SATA controller
    "sd_mod"      # SCSI disk support
    "sr_mod"      # CD-ROM support
    "virtio_blk"  # QEMU virtio block device
    "virtio_pci"  # QEMU virtio PCI
    "virtio_net"  # QEMU virtio network
    "uhci_hcd"    # USB 1.1 (QEMU default)
    "ehci_pci"    # USB 2.0
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "kvm-intel" ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
